# Cloudflare Pages Configuration
name = "woozi-countdown" # 원래 프로젝트 명칭으로 고정
compatibility_date = "2024-04-01"
pages_build_output_dir = "." # 정적 파일이 있는 루트 디렉토리 지정

[[d1_databases]]
binding = "DB"
database_name = "woozi-comments"
database_id = "23af8887-0395-4b71-afda-781b3dbb42c6"
